version: "3.5"

services:
  postgres:
    image: postgres:12.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exercise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  kafka:
    image: lensesio/fast-data-dev
    container_name: kafka
    ports:
      - "3030:3030"
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
    environment:
      ADV_HOST: 127.0.0.1
