management:
  # Enable monitoring endpoints
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    loggers:
      enabled: true

  endpoints:
    # Disable all endpoints other than the ones explicitly enabled
    enabled-by-default: false

    # Expose endpoints over REST
    web:
      exposure:
        include: "*"
      # Customize path mappings
      base-path: /api/meta
      path-mapping:
        info: /build
        health: /ready
